### ISSUE TITLE
Error IllegalStateException

### ISSUE THREAD

**Issue by Andrey-Voytenko** [Andrey-Voytenko/ExampleDataBinding#1]
05-23 08:29:26.602 16954-16954/tk.av.exampledatabinding E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: tk.av.exampledatabinding, PID: 16954
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{tk.av.exampledatabinding/tk.av.exampledatabinding.view.MainActivity}: java.lang.IllegalStateException: Required DataBindingComponent is null in class ActivityMainBinding. A BindingAdapter in net.droidlabs.mvvm.recyclerview.binding.RecyclerViewBindings is not static and requires an object to use, retrieved from the DataBindingComponent. If you don't use an inflation method taking a DataBindingComponent, use DataBindingUtil.setDefaultComponent or make all BindingAdapter methods static.
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: java.lang.IllegalStateException: Required DataBindingComponent is null in class ActivityMainBinding. A BindingAdapter in net.droidlabs.mvvm.recyclerview.binding.RecyclerViewBindings is not static and requires an object to use, retrieved from the DataBindingComponent. If you don't use an inflation method taking a DataBindingComponent, use DataBindingUtil.setDefaultComponent or make all BindingAdapter methods static.
                                                                              at android.databinding.ViewDataBinding.ensureBindingComponentIsNotNull(ViewDataBinding.java:522)
                                                                              at tk.av.exampledatabinding.databinding.ActivityMainBinding.<init>(ActivityMainBinding.java:26)
                                                                              at tk.av.exampledatabinding.databinding.ActivityMainBinding.bind(ActivityMainBinding.java:196)
                                                                              at android.databinding.DataBinderMapper.getDataBinder(DataBinderMapper.java:11)
                                                                              at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:185)
                                                                              at android.databinding.DataBindingUtil.bindToAddedViews(DataBindingUtil.java:299)
                                                                              at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:279)
                                                                              at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
                                                                              at tk.av.exampledatabinding.view.MainActivity.onCreate(MainActivity.java:29)
                                                                              at android.app.Activity.performCreate(Activity.java:6237)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by radzio** [comment]
Please use https://jitpack.io/#radzio/android-data-binding-recyclerview/0.1.0


`compile 'com.github.radzio:android-data-binding-recyclerview:0.1.0'`
